version: '3'

services:
    db:
        image: "matheusbsilva/salicweb-db"
        ports:
            - "5432:5432"
    web:
        image: "matheusbsilva/python-salicweb"
        command: "python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/salicweb
        ports:
            - "8000:8000"
        depends_on:
            - db
